#lang racket
(provide make-configuration
         configuration?
         configuration-width
         configuration-height
         configuration-board
         configuration-start
         configuration-dots
         configuration-powers
         configuration-ghost-starts
         board-big
         board-tiny
         make-pair
         pair?
         pair-fst
         pair-snd)

(require (only-in lang/htdp-intermediate-lambda make-posn posn? define-struct))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; GameConfiguration
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define-struct configuration [width height board start dots powers ghost-starts])

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Pair
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(struct pair [fst snd] #:transparent #:constructor-name make-pair)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Tiny Board
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(define player0-tiny (make-posn 2 2))
(define width-tiny 5)
(define height-tiny 5)

(define dots-tiny
  (list (make-posn 0 0)
        (make-posn 1 0)
        (make-posn 2 0)
        (make-posn 3 0)
        (make-posn 4 0)
        (make-posn 4 1)
        (make-posn 4 2)
        (make-posn 4 3)
        (make-posn 4 4)
        (make-posn 3 4)
        (make-posn 2 4)
        (make-posn 1 4)
        (make-posn 0 4)
        (make-posn 0 3)
        (make-posn 0 2)
        (make-posn 0 1)))

(define supers-tiny
  (list (make-posn 2 1)
        (make-posn 2 3)))

(define board-map-tiny
  (list
   (make-pair (make-posn 0 0) '("up" "left"))
   (make-pair (make-posn 1 0) '("up" "down"))
   (make-pair (make-posn 2 0) '("up"))
   (make-pair (make-posn 3 0) '("up" "down"))
   (make-pair (make-posn 4 0) '("up" "right"))
   (make-pair (make-posn 0 1) '("left" "right"))
   (make-pair (make-posn 1 1) '("up" "left" "right" "down"))
   (make-pair (make-posn 2 1) '("left" "right"))
   (make-pair (make-posn 3 1) '("up" "left" "right" "down"))
   (make-pair (make-posn 4 1) '("left" "right"))
   (make-pair (make-posn 0 2) '())
   (make-pair (make-posn 1 2) '("up" "down"))
   (make-pair (make-posn 2 2) '())
   (make-pair (make-posn 3 2) '("up" "down"))
   (make-pair (make-posn 4 2) '())
   (make-pair (make-posn 0 3) '("left" "right"))
   (make-pair (make-posn 1 3) '("up" "left" "right" "down"))
   (make-pair (make-posn 2 3) '("left" "right"))
   (make-pair (make-posn 3 3) '("up" "left" "right" "down"))
   (make-pair (make-posn 4 3) '("left" "right"))
   (make-pair (make-posn 0 4) '("left" "down"))
   (make-pair (make-posn 1 4) '("up" "down"))
   (make-pair (make-posn 2 4) '("down"))
   (make-pair (make-posn 3 4) '("up" "down"))
   (make-pair (make-posn 4 4) '("right" "down"))))

(define ghost-starts-tiny
  (list (make-posn 4 4)
        (make-posn 0 0)
        (make-posn 0 4)
        (make-posn 4 0)))

(define board-tiny
  (make-configuration width-tiny height-tiny board-map-tiny player0-tiny dots-tiny supers-tiny ghost-starts-tiny))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Big Board
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(define player0-big (make-posn 12 22))
(define width-big 26)
(define height-big 29)
(define dots-big
  (list
   (make-posn 0 0)
   (make-posn 0 1)
   (make-posn 0 3)
   (make-posn 0 4)
   (make-posn 0 5)
   (make-posn 0 6)
   (make-posn 0 7)
   (make-posn 0 19)
   (make-posn 0 20)
   (make-posn 0 21)
   (make-posn 0 25)
   (make-posn 0 26)
   (make-posn 0 27)
   (make-posn 0 28)
   (make-posn 1 0)
   (make-posn 1 4)
   (make-posn 1 7)
   (make-posn 1 19)
   (make-posn 1 22)
   (make-posn 1 25)
   (make-posn 1 28)
   (make-posn 2 0)
   (make-posn 2 4)
   (make-posn 2 7)
   (make-posn 2 19)
   (make-posn 2 22)
   (make-posn 2 23)
   (make-posn 2 24)
   (make-posn 2 25)
   (make-posn 2 28)
   (make-posn 3 0)
   (make-posn 3 4)
   (make-posn 3 7)
   (make-posn 3 19)
   (make-posn 3 25)
   (make-posn 3 28)
   (make-posn 4 0)
   (make-posn 4 4)
   (make-posn 4 7)
   (make-posn 4 19)
   (make-posn 4 25)
   (make-posn 4 28)
   (make-posn 5 0)
   (make-posn 5 1)
   (make-posn 5 2)
   (make-posn 5 3)
   (make-posn 5 4)
   (make-posn 5 5)
   (make-posn 5 6)
   (make-posn 5 7)
   (make-posn 5 8)
   (make-posn 5 9)
   (make-posn 5 10)
   (make-posn 5 11)
   (make-posn 5 12)
   (make-posn 5 13)
   (make-posn 5 14)
   (make-posn 5 15)
   (make-posn 5 16)
   (make-posn 5 17)
   (make-posn 5 18)
   (make-posn 5 19)
   (make-posn 5 20)
   (make-posn 5 21)
   (make-posn 5 22)
   (make-posn 5 23)
   (make-posn 5 24)
   (make-posn 5 25)
   (make-posn 5 28)
   (make-posn 6 0)
   (make-posn 6 4)
   (make-posn 6 19)
   (make-posn 6 22)
   (make-posn 6 28)
   (make-posn 7 0)
   (make-posn 7 4)
   (make-posn 7 19)
   (make-posn 7 22)
   (make-posn 7 28)
   (make-posn 8 0)
   (make-posn 8 4)
   (make-posn 8 5)
   (make-posn 8 6)
   (make-posn 8 7)
   (make-posn 8 19)
   (make-posn 8 22)
   (make-posn 8 23)
   (make-posn 8 24)
   (make-posn 8 25)
   (make-posn 8 28)
   (make-posn 9 0)
   (make-posn 9 4)
   (make-posn 9 7)
   (make-posn 9 19)
   (make-posn 9 22)
   (make-posn 9 25)
   (make-posn 9 28)
   (make-posn 10 0)
   (make-posn 10 4)
   (make-posn 10 7)
   (make-posn 10 19)
   (make-posn 10 22)
   (make-posn 10 25)
   (make-posn 10 28)
   (make-posn 11 0)
   (make-posn 11 1)
   (make-posn 11 2)
   (make-posn 11 3)
   (make-posn 11 4)
   (make-posn 11 7)
   (make-posn 11 19)
   (make-posn 11 20)
   (make-posn 11 21)
   (make-posn 11 22)
   (make-posn 11 25)
   (make-posn 11 26)
   (make-posn 11 27)
   (make-posn 11 28)
   (make-posn 12 4)
   (make-posn 12 22)
   (make-posn 12 28)
   (make-posn 13 4)
   (make-posn 13 22)
   (make-posn 13 28)
   (make-posn 14 0)
   (make-posn 14 1)
   (make-posn 14 2)
   (make-posn 14 3)
   (make-posn 14 4)
   (make-posn 14 7)
   (make-posn 14 19)
   (make-posn 14 20)
   (make-posn 14 21)
   (make-posn 14 22)
   (make-posn 14 25)
   (make-posn 14 26)
   (make-posn 14 27)
   (make-posn 14 28)
   (make-posn 15 0)
   (make-posn 15 4)
   (make-posn 15 7)
   (make-posn 15 19)
   (make-posn 15 22)
   (make-posn 15 25)
   (make-posn 15 28)
   (make-posn 16 0)
   (make-posn 16 4)
   (make-posn 16 7)
   (make-posn 16 19)
   (make-posn 16 22)
   (make-posn 16 25)
   (make-posn 16 28)
   (make-posn 17 0)
   (make-posn 17 4)
   (make-posn 17 5)
   (make-posn 17 6)
   (make-posn 17 7)
   (make-posn 17 19)
   (make-posn 17 22)
   (make-posn 17 23)
   (make-posn 17 24)
   (make-posn 17 25)
   (make-posn 17 28)
   (make-posn 18 0)
   (make-posn 18 4)
   (make-posn 18 19)
   (make-posn 18 22)
   (make-posn 18 28)
   (make-posn 19 0)
   (make-posn 19 4)
   (make-posn 19 19)
   (make-posn 19 22)
   (make-posn 19 28)
   (make-posn 20 0)
   (make-posn 20 1)
   (make-posn 20 2)
   (make-posn 20 3)
   (make-posn 20 4)
   (make-posn 20 5)
   (make-posn 20 6)
   (make-posn 20 7)
   (make-posn 20 8)
   (make-posn 20 9)
   (make-posn 20 10)
   (make-posn 20 11)
   (make-posn 20 12)
   (make-posn 20 13)
   (make-posn 20 14)
   (make-posn 20 15)
   (make-posn 20 16)
   (make-posn 20 17)
   (make-posn 20 18)
   (make-posn 20 19)
   (make-posn 20 20)
   (make-posn 20 21)
   (make-posn 20 22)
   (make-posn 20 23)
   (make-posn 20 24)
   (make-posn 20 25)
   (make-posn 20 28)
   (make-posn 21 0)
   (make-posn 21 4)
   (make-posn 21 7)
   (make-posn 21 19)
   (make-posn 21 25)
   (make-posn 21 28)
   (make-posn 22 0)
   (make-posn 22 4)
   (make-posn 22 7)
   (make-posn 22 19)
   (make-posn 22 25)
   (make-posn 22 28)
   (make-posn 23 0)
   (make-posn 23 4)
   (make-posn 23 7)
   (make-posn 23 19)
   (make-posn 23 22)
   (make-posn 23 23)
   (make-posn 23 24)
   (make-posn 23 25)
   (make-posn 23 28)
   (make-posn 24 0)
   (make-posn 24 4)
   (make-posn 24 7)
   (make-posn 24 19)
   (make-posn 24 22)
   (make-posn 24 25)
   (make-posn 24 28)
   (make-posn 25 0)
   (make-posn 25 1)
   (make-posn 25 3)
   (make-posn 25 4)
   (make-posn 25 5)
   (make-posn 25 6)
   (make-posn 25 7)
   (make-posn 25 19)
   (make-posn 25 20)
   (make-posn 25 21)
   (make-posn 25 25)
   (make-posn 25 26)
   (make-posn 25 27)
   (make-posn 25 28)))
(define supers-big
  (list
   (make-posn 0 2)
   (make-posn 0 22)
   (make-posn 25 2)
   (make-posn 25 22)))
(define board-map-big
  (list
   (make-pair (make-posn 0 0) '("up" "left"))
   (make-pair (make-posn 1 0) '("up" "down"))
   (make-pair (make-posn 2 0) '("up" "down"))
   (make-pair (make-posn 3 0) '("up" "down"))
   (make-pair (make-posn 4 0) '("up" "down"))
   (make-pair (make-posn 5 0) '("up"))
   (make-pair (make-posn 6 0) '("up" "down"))
   (make-pair (make-posn 7 0) '("up" "down"))
   (make-pair (make-posn 8 0) '("up" "down"))
   (make-pair (make-posn 9 0) '("up" "down"))
   (make-pair (make-posn 10 0) '("up" "down"))
   (make-pair (make-posn 11 0) '("up" "right"))
   (make-pair (make-posn 12 0) '("up" "left"))
   (make-pair (make-posn 13 0) '("up" "right"))
   (make-pair (make-posn 14 0) '("up" "left"))
   (make-pair (make-posn 15 0) '("up" "down"))
   (make-pair (make-posn 16 0) '("up" "down"))
   (make-pair (make-posn 17 0) '("up" "down"))
   (make-pair (make-posn 18 0) '("up" "down"))
   (make-pair (make-posn 19 0) '("up" "down"))
   (make-pair (make-posn 20 0) '("up"))
   (make-pair (make-posn 21 0) '("up" "down"))
   (make-pair (make-posn 22 0) '("up" "down"))
   (make-pair (make-posn 23 0) '("up" "down"))
   (make-pair (make-posn 24 0) '("up" "down"))
   (make-pair (make-posn 25 0) '("up" "right"))
   (make-pair (make-posn 0 1) '("left" "right"))
   (make-pair (make-posn 1 1) '("up" "left"))
   (make-pair (make-posn 2 1) '("up"))
   (make-pair (make-posn 3 1) '("up"))
   (make-pair (make-posn 4 1) '("up" "right"))
   (make-pair (make-posn 5 1) '("left" "right"))
   (make-pair (make-posn 6 1) '("up" "left"))
   (make-pair (make-posn 7 1) '("up"))
   (make-pair (make-posn 8 1) '("up"))
   (make-pair (make-posn 9 1) '("up"))
   (make-pair (make-posn 10 1) '("up" "right"))
   (make-pair (make-posn 11 1) '("left" "right"))
   (make-pair (make-posn 12 1) '("left"))
   (make-pair (make-posn 13 1) '("right"))
   (make-pair (make-posn 14 1) '("left" "right"))
   (make-pair (make-posn 15 1) '("up" "left"))
   (make-pair (make-posn 16 1) '("up"))
   (make-pair (make-posn 17 1) '("up"))
   (make-pair (make-posn 18 1) '("up"))
   (make-pair (make-posn 19 1) '("up" "right"))
   (make-pair (make-posn 20 1) '("left" "right"))
   (make-pair (make-posn 21 1) '("up" "left"))
   (make-pair (make-posn 22 1) '("up"))
   (make-pair (make-posn 23 1) '("up"))
   (make-pair (make-posn 24 1) '("up" "right"))
   (make-pair (make-posn 25 1) '("left" "right"))
   (make-pair (make-posn 0 2) '("left" "right"))
   (make-pair (make-posn 1 2) '("left"))
   (make-pair (make-posn 2 2) '())
   (make-pair (make-posn 3 2) '())
   (make-pair (make-posn 4 2) '("right"))
   (make-pair (make-posn 5 2) '("left" "right"))
   (make-pair (make-posn 6 2) '("left"))
   (make-pair (make-posn 7 2) '())
   (make-pair (make-posn 8 2) '())
   (make-pair (make-posn 9 2) '())
   (make-pair (make-posn 10 2) '("right"))
   (make-pair (make-posn 11 2) '("left" "right"))
   (make-pair (make-posn 12 2) '("left"))
   (make-pair (make-posn 13 2) '("right"))
   (make-pair (make-posn 14 2) '("left" "right"))
   (make-pair (make-posn 15 2) '("left"))
   (make-pair (make-posn 16 2) '())
   (make-pair (make-posn 17 2) '())
   (make-pair (make-posn 18 2) '())
   (make-pair (make-posn 19 2) '("right"))
   (make-pair (make-posn 20 2) '("left" "right"))
   (make-pair (make-posn 21 2) '("left"))
   (make-pair (make-posn 22 2) '())
   (make-pair (make-posn 23 2) '())
   (make-pair (make-posn 24 2) '("right"))
   (make-pair (make-posn 25 2) '("left" "right"))
   (make-pair (make-posn 0 3) '("left" "right"))
   (make-pair (make-posn 1 3) '("left" "down"))
   (make-pair (make-posn 2 3) '("down"))
   (make-pair (make-posn 3 3) '("down"))
   (make-pair (make-posn 4 3) '("right" "down"))
   (make-pair (make-posn 5 3) '("left" "right"))
   (make-pair (make-posn 6 3) '("left" "down"))
   (make-pair (make-posn 7 3) '("down"))
   (make-pair (make-posn 8 3) '("down"))
   (make-pair (make-posn 9 3) '("down"))
   (make-pair (make-posn 10 3) '("right" "down"))
   (make-pair (make-posn 11 3) '("left" "right"))
   (make-pair (make-posn 12 3) '("left" "down"))
   (make-pair (make-posn 13 3) '("right" "down"))
   (make-pair (make-posn 14 3) '("left" "right"))
   (make-pair (make-posn 15 3) '("left" "down"))
   (make-pair (make-posn 16 3) '("down"))
   (make-pair (make-posn 17 3) '("down"))
   (make-pair (make-posn 18 3) '("down"))
   (make-pair (make-posn 19 3) '("right" "down"))
   (make-pair (make-posn 20 3) '("left" "right"))
   (make-pair (make-posn 21 3) '("left" "down"))
   (make-pair (make-posn 22 3) '("down"))
   (make-pair (make-posn 23 3) '("down"))
   (make-pair (make-posn 24 3) '("right" "down"))
   (make-pair (make-posn 25 3) '("left" "right"))
   (make-pair (make-posn 0 4) '("left"))
   (make-pair (make-posn 1 4) '("up" "down"))
   (make-pair (make-posn 2 4) '("up" "down"))
   (make-pair (make-posn 3 4) '("up" "down"))
   (make-pair (make-posn 4 4) '("up" "down"))
   (make-pair (make-posn 5 4) '())
   (make-pair (make-posn 6 4) '("up" "down"))
   (make-pair (make-posn 7 4) '("up" "down"))
   (make-pair (make-posn 8 4) '("up"))
   (make-pair (make-posn 9 4) '("up" "down"))
   (make-pair (make-posn 10 4) '("up" "down"))
   (make-pair (make-posn 11 4) '("down"))
   (make-pair (make-posn 12 4) '("up" "down"))
   (make-pair (make-posn 13 4) '("up" "down"))
   (make-pair (make-posn 14 4) '("down"))
   (make-pair (make-posn 15 4) '("up" "down"))
   (make-pair (make-posn 16 4) '("up" "down"))
   (make-pair (make-posn 17 4) '("up"))
   (make-pair (make-posn 18 4) '("up" "down"))
   (make-pair (make-posn 19 4) '("up" "down"))
   (make-pair (make-posn 20 4) '())
   (make-pair (make-posn 21 4) '("up" "down"))
   (make-pair (make-posn 22 4) '("up" "down"))
   (make-pair (make-posn 23 4) '("up" "down"))
   (make-pair (make-posn 24 4) '("up" "down"))
   (make-pair (make-posn 25 4) '("right"))
   (make-pair (make-posn 0 5) '("left" "right"))
   (make-pair (make-posn 1 5) '("up" "left"))
   (make-pair (make-posn 2 5) '("up"))
   (make-pair (make-posn 3 5) '("up"))
   (make-pair (make-posn 4 5) '("up" "right"))
   (make-pair (make-posn 5 5) '("left" "right"))
   (make-pair (make-posn 6 5) '("up" "left"))
   (make-pair (make-posn 7 5) '("up" "right"))
   (make-pair (make-posn 8 5) '("left" "right"))
   (make-pair (make-posn 9 5) '("up" "left"))
   (make-pair (make-posn 10 5) '("up"))
   (make-pair (make-posn 11 5) '("up"))
   (make-pair (make-posn 12 5) '("up"))
   (make-pair (make-posn 13 5) '("up"))
   (make-pair (make-posn 14 5) '("up"))
   (make-pair (make-posn 15 5) '("up"))
   (make-pair (make-posn 16 5) '("up" "right"))
   (make-pair (make-posn 17 5) '("left" "right"))
   (make-pair (make-posn 18 5) '("up" "left"))
   (make-pair (make-posn 19 5) '("up" "right"))
   (make-pair (make-posn 20 5) '("left" "right"))
   (make-pair (make-posn 21 5) '("up" "left"))
   (make-pair (make-posn 22 5) '("up"))
   (make-pair (make-posn 23 5) '("up"))
   (make-pair (make-posn 24 5) '("up" "right"))
   (make-pair (make-posn 25 5) '("left" "right"))
   (make-pair (make-posn 0 6) '("left" "right"))
   (make-pair (make-posn 1 6) '("left" "down"))
   (make-pair (make-posn 2 6) '("down"))
   (make-pair (make-posn 3 6) '("down"))
   (make-pair (make-posn 4 6) '("right" "down"))
   (make-pair (make-posn 5 6) '("left" "right"))
   (make-pair (make-posn 6 6) '("left"))
   (make-pair (make-posn 7 6) '("right"))
   (make-pair (make-posn 8 6) '("left" "right"))
   (make-pair (make-posn 9 6) '("left" "down"))
   (make-pair (make-posn 10 6) '("down"))
   (make-pair (make-posn 11 6) '("down"))
   (make-pair (make-posn 12 6) '())
   (make-pair (make-posn 13 6) '())
   (make-pair (make-posn 14 6) '("down"))
   (make-pair (make-posn 15 6) '("down"))
   (make-pair (make-posn 16 6) '("right" "down"))
   (make-pair (make-posn 17 6) '("left" "right"))
   (make-pair (make-posn 18 6) '("left"))
   (make-pair (make-posn 19 6) '("right"))
   (make-pair (make-posn 20 6) '("left" "right"))
   (make-pair (make-posn 21 6) '("left" "down"))
   (make-pair (make-posn 22 6) '("down"))
   (make-pair (make-posn 23 6) '("down"))
   (make-pair (make-posn 24 6) '("right" "down"))
   (make-pair (make-posn 25 6) '("left" "right"))
   (make-pair (make-posn 0 7) '("left" "down"))
   (make-pair (make-posn 1 7) '("up" "down"))
   (make-pair (make-posn 2 7) '("up" "down"))
   (make-pair (make-posn 3 7) '("up" "down"))
   (make-pair (make-posn 4 7) '("up" "down"))
   (make-pair (make-posn 5 7) '("right"))
   (make-pair (make-posn 6 7) '("left"))
   (make-pair (make-posn 7 7) '("right"))
   (make-pair (make-posn 8 7) '("left" "down"))
   (make-pair (make-posn 9 7) '("up" "down"))
   (make-pair (make-posn 10 7) '("up" "down"))
   (make-pair (make-posn 11 7) '("up" "right"))
   (make-pair (make-posn 12 7) '("left"))
   (make-pair (make-posn 13 7) '("right"))
   (make-pair (make-posn 14 7) '("up" "left"))
   (make-pair (make-posn 15 7) '("up" "down"))
   (make-pair (make-posn 16 7) '("up" "down"))
   (make-pair (make-posn 17 7) '("right" "down"))
   (make-pair (make-posn 18 7) '("left"))
   (make-pair (make-posn 19 7) '("right"))
   (make-pair (make-posn 20 7) '("left"))
   (make-pair (make-posn 21 7) '("up" "down"))
   (make-pair (make-posn 22 7) '("up" "down"))
   (make-pair (make-posn 23 7) '("up" "down"))
   (make-pair (make-posn 24 7) '("up" "down"))
   (make-pair (make-posn 25 7) '("right" "down"))
   (make-pair (make-posn 0 8) '("up" "left"))
   (make-pair (make-posn 1 8) '("up"))
   (make-pair (make-posn 2 8) '("up"))
   (make-pair (make-posn 3 8) '("up"))
   (make-pair (make-posn 4 8) '("up" "right"))
   (make-pair (make-posn 5 8) '("left" "right"))
   (make-pair (make-posn 6 8) '("left"))
   (make-pair (make-posn 7 8) '())
   (make-pair (make-posn 8 8) '("up"))
   (make-pair (make-posn 9 8) '("up"))
   (make-pair (make-posn 10 8) '("up" "right"))
   (make-pair (make-posn 11 8) '("left" "right"))
   (make-pair (make-posn 12 8) '("left"))
   (make-pair (make-posn 13 8) '("right"))
   (make-pair (make-posn 14 8) '("left" "right"))
   (make-pair (make-posn 15 8) '("up" "left"))
   (make-pair (make-posn 16 8) '("up"))
   (make-pair (make-posn 17 8) '("up"))
   (make-pair (make-posn 18 8) '())
   (make-pair (make-posn 19 8) '("right"))
   (make-pair (make-posn 20 8) '("left" "right"))
   (make-pair (make-posn 21 8) '("up" "left"))
   (make-pair (make-posn 22 8) '("up"))
   (make-pair (make-posn 23 8) '("up"))
   (make-pair (make-posn 24 8) '("up"))
   (make-pair (make-posn 25 8) '("up" "right"))
   (make-pair (make-posn 0 9) '("left"))
   (make-pair (make-posn 1 9) '())
   (make-pair (make-posn 2 9) '())
   (make-pair (make-posn 3 9) '())
   (make-pair (make-posn 4 9) '("right"))
   (make-pair (make-posn 5 9) '("left" "right"))
   (make-pair (make-posn 6 9) '("left"))
   (make-pair (make-posn 7 9) '())
   (make-pair (make-posn 8 9) '("down"))
   (make-pair (make-posn 9 9) '("down"))
   (make-pair (make-posn 10 9) '("right" "down"))
   (make-pair (make-posn 11 9) '("left" "right"))
   (make-pair (make-posn 12 9) '("left" "down"))
   (make-pair (make-posn 13 9) '("right" "down"))
   (make-pair (make-posn 14 9) '("left" "right"))
   (make-pair (make-posn 15 9) '("left" "down"))
   (make-pair (make-posn 16 9) '("down"))
   (make-pair (make-posn 17 9) '("down"))
   (make-pair (make-posn 18 9) '())
   (make-pair (make-posn 19 9) '("right"))
   (make-pair (make-posn 20 9) '("left" "right"))
   (make-pair (make-posn 21 9) '("left"))
   (make-pair (make-posn 22 9) '())
   (make-pair (make-posn 23 9) '())
   (make-pair (make-posn 24 9) '())
   (make-pair (make-posn 25 9) '("right"))
   (make-pair (make-posn 0 10) '("left"))
   (make-pair (make-posn 1 10) '())
   (make-pair (make-posn 2 10) '())
   (make-pair (make-posn 3 10) '())
   (make-pair (make-posn 4 10) '("right"))
   (make-pair (make-posn 5 10) '("left" "right"))
   (make-pair (make-posn 6 10) '("left"))
   (make-pair (make-posn 7 10) '("right"))
   (make-pair (make-posn 8 10) '("up" "left"))
   (make-pair (make-posn 9 10) '("up"))
   (make-pair (make-posn 10 10) '("up"))
   (make-pair (make-posn 11 10) '())
   (make-pair (make-posn 12 10) '("up"))
   (make-pair (make-posn 13 10) '("up"))
   (make-pair (make-posn 14 10) '())
   (make-pair (make-posn 15 10) '("up"))
   (make-pair (make-posn 16 10) '("up"))
   (make-pair (make-posn 17 10) '("up" "right"))
   (make-pair (make-posn 18 10) '("left"))
   (make-pair (make-posn 19 10) '("right"))
   (make-pair (make-posn 20 10) '("left" "right"))
   (make-pair (make-posn 21 10) '("left"))
   (make-pair (make-posn 22 10) '())
   (make-pair (make-posn 23 10) '())
   (make-pair (make-posn 24 10) '())
   (make-pair (make-posn 25 10) '("right"))
   (make-pair (make-posn 0 11) '("left"))
   (make-pair (make-posn 1 11) '())
   (make-pair (make-posn 2 11) '())
   (make-pair (make-posn 3 11) '())
   (make-pair (make-posn 4 11) '("right"))
   (make-pair (make-posn 5 11) '("left" "right"))
   (make-pair (make-posn 6 11) '("left"))
   (make-pair (make-posn 7 11) '("right"))
   (make-pair (make-posn 8 11) '("left"))
   (make-pair (make-posn 9 11) '("down"))
   (make-pair (make-posn 10 11) '("down"))
   (make-pair (make-posn 11 11) '("down"))
   (make-pair (make-posn 12 11) '("down"))
   (make-pair (make-posn 13 11) '("down"))
   (make-pair (make-posn 14 11) '("down"))
   (make-pair (make-posn 15 11) '("down"))
   (make-pair (make-posn 16 11) '("down"))
   (make-pair (make-posn 17 11) '("right"))
   (make-pair (make-posn 18 11) '("left"))
   (make-pair (make-posn 19 11) '("right"))
   (make-pair (make-posn 20 11) '("left" "right"))
   (make-pair (make-posn 21 11) '("left"))
   (make-pair (make-posn 22 11) '())
   (make-pair (make-posn 23 11) '())
   (make-pair (make-posn 24 11) '())
   (make-pair (make-posn 25 11) '("right"))
   (make-pair (make-posn 0 12) '("left" "down"))
   (make-pair (make-posn 1 12) '("down"))
   (make-pair (make-posn 2 12) '("down"))
   (make-pair (make-posn 3 12) '("down"))
   (make-pair (make-posn 4 12) '("right" "down"))
   (make-pair (make-posn 5 12) '("left" "right"))
   (make-pair (make-posn 6 12) '("left" "down"))
   (make-pair (make-posn 7 12) '("right" "down"))
   (make-pair (make-posn 8 12) '("left" "right"))
   (make-pair (make-posn 9 12) '("up" "left"))
   (make-pair (make-posn 10 12) '("up"))
   (make-pair (make-posn 11 12) '("up"))
   (make-pair (make-posn 12 12) '("up"))
   (make-pair (make-posn 13 12) '("up"))
   (make-pair (make-posn 14 12) '("up"))
   (make-pair (make-posn 15 12) '("up"))
   (make-pair (make-posn 16 12) '("up" "right"))
   (make-pair (make-posn 17 12) '("left" "right"))
   (make-pair (make-posn 18 12) '("left" "down"))
   (make-pair (make-posn 19 12) '("right" "down"))
   (make-pair (make-posn 20 12) '("left" "right"))
   (make-pair (make-posn 21 12) '("left" "down"))
   (make-pair (make-posn 22 12) '("down"))
   (make-pair (make-posn 23 12) '("down"))
   (make-pair (make-posn 24 12) '("down"))
   (make-pair (make-posn 25 12) '("right" "down"))
   (make-pair (make-posn 0 13) '("up" "down"))
   (make-pair (make-posn 1 13) '("up" "down"))
   (make-pair (make-posn 2 13) '("up" "down"))
   (make-pair (make-posn 3 13) '("up" "down"))
   (make-pair (make-posn 4 13) '("up" "down"))
   (make-pair (make-posn 5 13) '())
   (make-pair (make-posn 6 13) '("up" "down"))
   (make-pair (make-posn 7 13) '("up" "down"))
   (make-pair (make-posn 8 13) '("right"))
   (make-pair (make-posn 9 13) '("left"))
   (make-pair (make-posn 10 13) '())
   (make-pair (make-posn 11 13) '())
   (make-pair (make-posn 12 13) '())
   (make-pair (make-posn 13 13) '())
   (make-pair (make-posn 14 13) '())
   (make-pair (make-posn 15 13) '())
   (make-pair (make-posn 16 13) '("right"))
   (make-pair (make-posn 17 13) '("left"))
   (make-pair (make-posn 18 13) '("up" "down"))
   (make-pair (make-posn 19 13) '("up" "down"))
   (make-pair (make-posn 20 13) '())
   (make-pair (make-posn 21 13) '("up" "down"))
   (make-pair (make-posn 22 13) '("up" "down"))
   (make-pair (make-posn 23 13) '("up" "down"))
   (make-pair (make-posn 24 13) '("up" "down"))
   (make-pair (make-posn 25 13) '("up" "down"))
   (make-pair (make-posn 0 14) '("up" "left"))
   (make-pair (make-posn 1 14) '("up"))
   (make-pair (make-posn 2 14) '("up"))
   (make-pair (make-posn 3 14) '("up"))
   (make-pair (make-posn 4 14) '("up" "right"))
   (make-pair (make-posn 5 14) '("left" "right"))
   (make-pair (make-posn 6 14) '("up" "left"))
   (make-pair (make-posn 7 14) '("up" "right"))
   (make-pair (make-posn 8 14) '("left" "right"))
   (make-pair (make-posn 9 14) '("left"))
   (make-pair (make-posn 10 14) '())
   (make-pair (make-posn 11 14) '())
   (make-pair (make-posn 12 14) '())
   (make-pair (make-posn 13 14) '())
   (make-pair (make-posn 14 14) '())
   (make-pair (make-posn 15 14) '())
   (make-pair (make-posn 16 14) '("right"))
   (make-pair (make-posn 17 14) '("left" "right"))
   (make-pair (make-posn 18 14) '("up" "left"))
   (make-pair (make-posn 19 14) '("up" "right"))
   (make-pair (make-posn 20 14) '("left" "right"))
   (make-pair (make-posn 21 14) '("up" "left"))
   (make-pair (make-posn 22 14) '("up"))
   (make-pair (make-posn 23 14) '("up"))
   (make-pair (make-posn 24 14) '("up"))
   (make-pair (make-posn 25 14) '("up" "right"))
   (make-pair (make-posn 0 15) '("left"))
   (make-pair (make-posn 1 15) '())
   (make-pair (make-posn 2 15) '())
   (make-pair (make-posn 3 15) '())
   (make-pair (make-posn 4 15) '("right"))
   (make-pair (make-posn 5 15) '("left" "right"))
   (make-pair (make-posn 6 15) '("left"))
   (make-pair (make-posn 7 15) '("right"))
   (make-pair (make-posn 8 15) '("left" "right"))
   (make-pair (make-posn 9 15) '("left" "down"))
   (make-pair (make-posn 10 15) '("down"))
   (make-pair (make-posn 11 15) '("down"))
   (make-pair (make-posn 12 15) '("down"))
   (make-pair (make-posn 13 15) '("down"))
   (make-pair (make-posn 14 15) '("down"))
   (make-pair (make-posn 15 15) '("down"))
   (make-pair (make-posn 16 15) '("right" "down"))
   (make-pair (make-posn 17 15) '("left" "right"))
   (make-pair (make-posn 18 15) '("left"))
   (make-pair (make-posn 19 15) '("right"))
   (make-pair (make-posn 20 15) '("left" "right"))
   (make-pair (make-posn 21 15) '("left"))
   (make-pair (make-posn 22 15) '())
   (make-pair (make-posn 23 15) '())
   (make-pair (make-posn 24 15) '())
   (make-pair (make-posn 25 15) '("right"))
   (make-pair (make-posn 0 16) '("left"))
   (make-pair (make-posn 1 16) '())
   (make-pair (make-posn 2 16) '())
   (make-pair (make-posn 3 16) '())
   (make-pair (make-posn 4 16) '("right"))
   (make-pair (make-posn 5 16) '("left" "right"))
   (make-pair (make-posn 6 16) '("left"))
   (make-pair (make-posn 7 16) '("right"))
   (make-pair (make-posn 8 16) '("left"))
   (make-pair (make-posn 9 16) '("up" "down"))
   (make-pair (make-posn 10 16) '("up" "down"))
   (make-pair (make-posn 11 16) '("up" "down"))
   (make-pair (make-posn 12 16) '("up" "down"))
   (make-pair (make-posn 13 16) '("up" "down"))
   (make-pair (make-posn 14 16) '("up" "down"))
   (make-pair (make-posn 15 16) '("up" "down"))
   (make-pair (make-posn 16 16) '("up" "down"))
   (make-pair (make-posn 17 16) '("right"))
   (make-pair (make-posn 18 16) '("left"))
   (make-pair (make-posn 19 16) '("right"))
   (make-pair (make-posn 20 16) '("left" "right"))
   (make-pair (make-posn 21 16) '("left"))
   (make-pair (make-posn 22 16) '())
   (make-pair (make-posn 23 16) '())
   (make-pair (make-posn 24 16) '())
   (make-pair (make-posn 25 16) '("right"))
   (make-pair (make-posn 0 17) '("left"))
   (make-pair (make-posn 1 17) '())
   (make-pair (make-posn 2 17) '())
   (make-pair (make-posn 3 17) '())
   (make-pair (make-posn 4 17) '("right"))
   (make-pair (make-posn 5 17) '("left" "right"))
   (make-pair (make-posn 6 17) '("left"))
   (make-pair (make-posn 7 17) '("right"))
   (make-pair (make-posn 8 17) '("left" "right"))
   (make-pair (make-posn 9 17) '("up" "left"))
   (make-pair (make-posn 10 17) '("up"))
   (make-pair (make-posn 11 17) '("up"))
   (make-pair (make-posn 12 17) '("up"))
   (make-pair (make-posn 13 17) '("up"))
   (make-pair (make-posn 14 17) '("up"))
   (make-pair (make-posn 15 17) '("up"))
   (make-pair (make-posn 16 17) '("up" "right"))
   (make-pair (make-posn 17 17) '("left" "right"))
   (make-pair (make-posn 18 17) '("left"))
   (make-pair (make-posn 19 17) '("right"))
   (make-pair (make-posn 20 17) '("left" "right"))
   (make-pair (make-posn 21 17) '("left"))
   (make-pair (make-posn 22 17) '())
   (make-pair (make-posn 23 17) '())
   (make-pair (make-posn 24 17) '())
   (make-pair (make-posn 25 17) '("right"))
   (make-pair (make-posn 0 18) '("left" "down"))
   (make-pair (make-posn 1 18) '("down"))
   (make-pair (make-posn 2 18) '("down"))
   (make-pair (make-posn 3 18) '("down"))
   (make-pair (make-posn 4 18) '("right" "down"))
   (make-pair (make-posn 5 18) '("left" "right"))
   (make-pair (make-posn 6 18) '("left" "down"))
   (make-pair (make-posn 7 18) '("right" "down"))
   (make-pair (make-posn 8 18) '("left" "right"))
   (make-pair (make-posn 9 18) '("left" "down"))
   (make-pair (make-posn 10 18) '("down"))
   (make-pair (make-posn 11 18) '("down"))
   (make-pair (make-posn 12 18) '())
   (make-pair (make-posn 13 18) '())
   (make-pair (make-posn 14 18) '("down"))
   (make-pair (make-posn 15 18) '("down"))
   (make-pair (make-posn 16 18) '("right" "down"))
   (make-pair (make-posn 17 18) '("left" "right"))
   (make-pair (make-posn 18 18) '("left" "down"))
   (make-pair (make-posn 19 18) '("right" "down"))
   (make-pair (make-posn 20 18) '("left" "right"))
   (make-pair (make-posn 21 18) '("left" "down"))
   (make-pair (make-posn 22 18) '("down"))
   (make-pair (make-posn 23 18) '("down"))
   (make-pair (make-posn 24 18) '("down"))
   (make-pair (make-posn 25 18) '("right" "down"))
   (make-pair (make-posn 0 19) '("up" "left"))
   (make-pair (make-posn 1 19) '("up" "down"))
   (make-pair (make-posn 2 19) '("up" "down"))
   (make-pair (make-posn 3 19) '("up" "down"))
   (make-pair (make-posn 4 19) '("up" "down"))
   (make-pair (make-posn 5 19) '())
   (make-pair (make-posn 6 19) '("up" "down"))
   (make-pair (make-posn 7 19) '("up" "down"))
   (make-pair (make-posn 8 19) '("down"))
   (make-pair (make-posn 9 19) '("up" "down"))
   (make-pair (make-posn 10 19) '("up" "down"))
   (make-pair (make-posn 11 19) '("up" "right"))
   (make-pair (make-posn 12 19) '("left"))
   (make-pair (make-posn 13 19) '("right"))
   (make-pair (make-posn 14 19) '("up" "left"))
   (make-pair (make-posn 15 19) '("up" "down"))
   (make-pair (make-posn 16 19) '("up" "down"))
   (make-pair (make-posn 17 19) '("down"))
   (make-pair (make-posn 18 19) '("up" "down"))
   (make-pair (make-posn 19 19) '("up" "down"))
   (make-pair (make-posn 20 19) '())
   (make-pair (make-posn 21 19) '("up" "down"))
   (make-pair (make-posn 22 19) '("up" "down"))
   (make-pair (make-posn 23 19) '("up" "down"))
   (make-pair (make-posn 24 19) '("up" "down"))
   (make-pair (make-posn 25 19) '("up" "right"))
   (make-pair (make-posn 0 20) '("left" "right"))
   (make-pair (make-posn 1 20) '("up" "left"))
   (make-pair (make-posn 2 20) '("up"))
   (make-pair (make-posn 3 20) '("up"))
   (make-pair (make-posn 4 20) '("up" "right"))
   (make-pair (make-posn 5 20) '("left" "right"))
   (make-pair (make-posn 6 20) '("up" "left"))
   (make-pair (make-posn 7 20) '("up"))
   (make-pair (make-posn 8 20) '("up"))
   (make-pair (make-posn 9 20) '("up"))
   (make-pair (make-posn 10 20) '("up" "right"))
   (make-pair (make-posn 11 20) '("left" "right"))
   (make-pair (make-posn 12 20) '("left"))
   (make-pair (make-posn 13 20) '("right"))
   (make-pair (make-posn 14 20) '("left" "right"))
   (make-pair (make-posn 15 20) '("up" "left"))
   (make-pair (make-posn 16 20) '("up"))
   (make-pair (make-posn 17 20) '("up"))
   (make-pair (make-posn 18 20) '("up"))
   (make-pair (make-posn 19 20) '("up" "right"))
   (make-pair (make-posn 20 20) '("left" "right"))
   (make-pair (make-posn 21 20) '("up" "left"))
   (make-pair (make-posn 22 20) '("up"))
   (make-pair (make-posn 23 20) '("up"))
   (make-pair (make-posn 24 20) '("up" "right"))
   (make-pair (make-posn 25 20) '("left" "right"))
   (make-pair (make-posn 0 21) '("left" "right"))
   (make-pair (make-posn 1 21) '("left" "down"))
   (make-pair (make-posn 2 21) '("down"))
   (make-pair (make-posn 3 21) '())
   (make-pair (make-posn 4 21) '("right"))
   (make-pair (make-posn 5 21) '("left" "right"))
   (make-pair (make-posn 6 21) '("left" "down"))
   (make-pair (make-posn 7 21) '("down"))
   (make-pair (make-posn 8 21) '("down"))
   (make-pair (make-posn 9 21) '("down"))
   (make-pair (make-posn 10 21) '("right" "down"))
   (make-pair (make-posn 11 21) '("left" "right"))
   (make-pair (make-posn 12 21) '("left" "down"))
   (make-pair (make-posn 13 21) '("right" "down"))
   (make-pair (make-posn 14 21) '("left" "right"))
   (make-pair (make-posn 15 21) '("left" "down"))
   (make-pair (make-posn 16 21) '("down"))
   (make-pair (make-posn 17 21) '("down"))
   (make-pair (make-posn 18 21) '("down"))
   (make-pair (make-posn 19 21) '("right" "down"))
   (make-pair (make-posn 20 21) '("left" "right"))
   (make-pair (make-posn 21 21) '("left"))
   (make-pair (make-posn 22 21) '())
   (make-pair (make-posn 23 21) '("down"))
   (make-pair (make-posn 24 21) '("right" "down"))
   (make-pair (make-posn 25 21) '("left" "right"))
   (make-pair (make-posn 0 22) '("left" "down"))
   (make-pair (make-posn 1 22) '("up" "down"))
   (make-pair (make-posn 2 22) '("up" "right"))
   (make-pair (make-posn 3 22) '("left"))
   (make-pair (make-posn 4 22) '("right"))
   (make-pair (make-posn 5 22) '("left"))
   (make-pair (make-posn 6 22) '("up" "down"))
   (make-pair (make-posn 7 22) '("up" "down"))
   (make-pair (make-posn 8 22) '("up"))
   (make-pair (make-posn 9 22) '("up" "down"))
   (make-pair (make-posn 10 22) '("up" "down"))
   (make-pair (make-posn 11 22) '("down"))
   (make-pair (make-posn 12 22) '("up" "down"))
   (make-pair (make-posn 13 22) '("up" "down"))
   (make-pair (make-posn 14 22) '("down"))
   (make-pair (make-posn 15 22) '("up" "down"))
   (make-pair (make-posn 16 22) '("up" "down"))
   (make-pair (make-posn 17 22) '("up"))
   (make-pair (make-posn 18 22) '("up" "down"))
   (make-pair (make-posn 19 22) '("up" "down"))
   (make-pair (make-posn 20 22) '("right"))
   (make-pair (make-posn 21 22) '("left"))
   (make-pair (make-posn 22 22) '("right"))
   (make-pair (make-posn 23 22) '("up" "left"))
   (make-pair (make-posn 24 22) '("up" "down"))
   (make-pair (make-posn 25 22) '("right" "down"))
   (make-pair (make-posn 0 23) '("up" "left"))
   (make-pair (make-posn 1 23) '("up" "right"))
   (make-pair (make-posn 2 23) '("left" "right"))
   (make-pair (make-posn 3 23) '("left"))
   (make-pair (make-posn 4 23) '("right"))
   (make-pair (make-posn 5 23) '("left" "right"))
   (make-pair (make-posn 6 23) '("up" "left"))
   (make-pair (make-posn 7 23) '("up" "right"))
   (make-pair (make-posn 8 23) '("left" "right"))
   (make-pair (make-posn 9 23) '("up" "left"))
   (make-pair (make-posn 10 23) '("up"))
   (make-pair (make-posn 11 23) '("up"))
   (make-pair (make-posn 12 23) '("up"))
   (make-pair (make-posn 13 23) '("up"))
   (make-pair (make-posn 14 23) '("up"))
   (make-pair (make-posn 15 23) '("up"))
   (make-pair (make-posn 16 23) '("up" "right"))
   (make-pair (make-posn 17 23) '("left" "right"))
   (make-pair (make-posn 18 23) '("up" "left"))
   (make-pair (make-posn 19 23) '("up" "right"))
   (make-pair (make-posn 20 23) '("left" "right"))
   (make-pair (make-posn 21 23) '("left"))
   (make-pair (make-posn 22 23) '("right"))
   (make-pair (make-posn 23 23) '("left" "right"))
   (make-pair (make-posn 24 23) '("up" "left"))
   (make-pair (make-posn 25 23) '("up" "right"))
   (make-pair (make-posn 0 24) '("left" "down"))
   (make-pair (make-posn 1 24) '("right" "down"))
   (make-pair (make-posn 2 24) '("left" "right"))
   (make-pair (make-posn 3 24) '("left" "down"))
   (make-pair (make-posn 4 24) '("right" "down"))
   (make-pair (make-posn 5 24) '("left" "right"))
   (make-pair (make-posn 6 24) '("left"))
   (make-pair (make-posn 7 24) '("right"))
   (make-pair (make-posn 8 24) '("left" "right"))
   (make-pair (make-posn 9 24) '("left" "down"))
   (make-pair (make-posn 10 24) '("down"))
   (make-pair (make-posn 11 24) '("down"))
   (make-pair (make-posn 12 24) '())
   (make-pair (make-posn 13 24) '())
   (make-pair (make-posn 14 24) '("down"))
   (make-pair (make-posn 15 24) '("down"))
   (make-pair (make-posn 16 24) '("right" "down"))
   (make-pair (make-posn 17 24) '("left" "right"))
   (make-pair (make-posn 18 24) '("left"))
   (make-pair (make-posn 19 24) '("right"))
   (make-pair (make-posn 20 24) '("left" "right"))
   (make-pair (make-posn 21 24) '("left" "down"))
   (make-pair (make-posn 22 24) '("right" "down"))
   (make-pair (make-posn 23 24) '("left" "right"))
   (make-pair (make-posn 24 24) '("left" "down"))
   (make-pair (make-posn 25 24) '("right" "down"))
   (make-pair (make-posn 0 25) '("up" "left"))
   (make-pair (make-posn 1 25) '("up" "down"))
   (make-pair (make-posn 2 25) '("down"))
   (make-pair (make-posn 3 25) '("up" "down"))
   (make-pair (make-posn 4 25) '("up" "down"))
   (make-pair (make-posn 5 25) '("right" "down"))
   (make-pair (make-posn 6 25) '("left"))
   (make-pair (make-posn 7 25) '("right"))
   (make-pair (make-posn 8 25) '("left" "down"))
   (make-pair (make-posn 9 25) '("up" "down"))
   (make-pair (make-posn 10 25) '("up" "down"))
   (make-pair (make-posn 11 25) '("up" "right"))
   (make-pair (make-posn 12 25) '("left"))
   (make-pair (make-posn 13 25) '("right"))
   (make-pair (make-posn 14 25) '("up" "left"))
   (make-pair (make-posn 15 25) '("up" "down"))
   (make-pair (make-posn 16 25) '("up" "down"))
   (make-pair (make-posn 17 25) '("right" "down"))
   (make-pair (make-posn 18 25) '("left"))
   (make-pair (make-posn 19 25) '("right"))
   (make-pair (make-posn 20 25) '("left" "down"))
   (make-pair (make-posn 21 25) '("up" "down"))
   (make-pair (make-posn 22 25) '("up" "down"))
   (make-pair (make-posn 23 25) '("down"))
   (make-pair (make-posn 24 25) '("up" "down"))
   (make-pair (make-posn 25 25) '("up" "right"))
   (make-pair (make-posn 0 26) '("left" "right"))
   (make-pair (make-posn 1 26) '("up" "left"))
   (make-pair (make-posn 2 26) '("up"))
   (make-pair (make-posn 3 26) '("up"))
   (make-pair (make-posn 4 26) '("up"))
   (make-pair (make-posn 5 26) '("up"))
   (make-pair (make-posn 6 26) '())
   (make-pair (make-posn 7 26) '())
   (make-pair (make-posn 8 26) '("up"))
   (make-pair (make-posn 9 26) '("up"))
   (make-pair (make-posn 10 26) '("up" "right"))
   (make-pair (make-posn 11 26) '("left" "right"))
   (make-pair (make-posn 12 26) '("left"))
   (make-pair (make-posn 13 26) '("right"))
   (make-pair (make-posn 14 26) '("left" "right"))
   (make-pair (make-posn 15 26) '("up" "left"))
   (make-pair (make-posn 16 26) '("up"))
   (make-pair (make-posn 17 26) '("up"))
   (make-pair (make-posn 18 26) '())
   (make-pair (make-posn 19 26) '())
   (make-pair (make-posn 20 26) '("up"))
   (make-pair (make-posn 21 26) '("up"))
   (make-pair (make-posn 22 26) '("up"))
   (make-pair (make-posn 23 26) '("up"))
   (make-pair (make-posn 24 26) '("up" "right"))
   (make-pair (make-posn 25 26) '("left" "right"))
   (make-pair (make-posn 0 27) '("left" "right"))
   (make-pair (make-posn 1 27) '("left" "down"))
   (make-pair (make-posn 2 27) '("down"))
   (make-pair (make-posn 3 27) '("down"))
   (make-pair (make-posn 4 27) '("down"))
   (make-pair (make-posn 5 27) '("down"))
   (make-pair (make-posn 6 27) '("down"))
   (make-pair (make-posn 7 27) '("down"))
   (make-pair (make-posn 8 27) '("down"))
   (make-pair (make-posn 9 27) '("down"))
   (make-pair (make-posn 10 27) '("right" "down"))
   (make-pair (make-posn 11 27) '("left" "right"))
   (make-pair (make-posn 12 27) '("left" "down"))
   (make-pair (make-posn 13 27) '("right" "down"))
   (make-pair (make-posn 14 27) '("left" "right"))
   (make-pair (make-posn 15 27) '("left" "down"))
   (make-pair (make-posn 16 27) '("down"))
   (make-pair (make-posn 17 27) '("down"))
   (make-pair (make-posn 18 27) '("down"))
   (make-pair (make-posn 19 27) '("down"))
   (make-pair (make-posn 20 27) '("down"))
   (make-pair (make-posn 21 27) '("down"))
   (make-pair (make-posn 22 27) '("down"))
   (make-pair (make-posn 23 27) '("down"))
   (make-pair (make-posn 24 27) '("right" "down"))
   (make-pair (make-posn 25 27) '("left" "right"))
   (make-pair (make-posn 0 28) '("left" "down"))
   (make-pair (make-posn 1 28) '("up" "down"))
   (make-pair (make-posn 2 28) '("up" "down"))
   (make-pair (make-posn 3 28) '("up" "down"))
   (make-pair (make-posn 4 28) '("up" "down"))
   (make-pair (make-posn 5 28) '("up" "down"))
   (make-pair (make-posn 6 28) '("up" "down"))
   (make-pair (make-posn 7 28) '("up" "down"))
   (make-pair (make-posn 8 28) '("up" "down"))
   (make-pair (make-posn 9 28) '("up" "down"))
   (make-pair (make-posn 10 28) '("up" "down"))
   (make-pair (make-posn 11 28) '("down"))
   (make-pair (make-posn 12 28) '("up" "down"))
   (make-pair (make-posn 13 28) '("up" "down"))
   (make-pair (make-posn 14 28) '("down"))
   (make-pair (make-posn 15 28) '("up" "down"))
   (make-pair (make-posn 16 28) '("up" "down"))
   (make-pair (make-posn 17 28) '("up" "down"))
   (make-pair (make-posn 18 28) '("up" "down"))
   (make-pair (make-posn 19 28) '("up" "down"))
   (make-pair (make-posn 20 28) '("up" "down"))
   (make-pair (make-posn 21 28) '("up" "down"))
   (make-pair (make-posn 22 28) '("up" "down"))
   (make-pair (make-posn 23 28) '("up" "down"))
   (make-pair (make-posn 24 28) '("up" "down"))
   (make-pair (make-posn 25 28) '("right" "down"))))
(define ghost-starts-big
  (list (make-posn 5 4)
        (make-posn 20 4)
        (make-posn 5 20)
        (make-posn 20 20)))

(define board-big
  (make-configuration width-big height-big board-map-big player0-big dots-big supers-big ghost-starts-big))
